/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game.GUI;

import GUI.BaseChildFrame;
import GUI.MainMenu;
import static Game.GUI.Game.addTextToButton;
import Game.Chapters.Game_Chapter_1;
import Game.Chapters.Game_Chapter_2;
import Game.Chapters.Game_Chapter_3;
import Game.Chapters.Game_Chapter_4;
import Game.Chapters.Game_Chapter_5;
import Game.Chapters.Game_Chapter_6;
import Game.Chapters.Game_Chapter_7;
import Game.Chapters.Game_Chapter_8;
import Game.Chapters.Game_Chapter_9;
import GameUtilities.Background;
import GameUtilities.Sound_Player;
import static java.awt.Toolkit.getDefaultToolkit;

/**
 *
 * @author Skel&Targarian
 */
public class Game_Adventure extends BaseChildFrame {

    //номер - номер ячейки списка, который выводится. Это текст приключения.
    public static int level = 1;
    
    
    Game_Chapter_1 gChapter;
    Game game;
    

    /**
     * Creates new form Game_Adventure
     */
    public Game_Adventure()
      {
         initComponents();
         createNameChapter();   
         quickly.setEnabled(false);     
         textAdventure.setFont(MainMenu.customFont);
         this.setIconImage(getDefaultToolkit().getImage(getClass().getResource("555.png")));
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        start = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAdventure = new javax.swing.JTextArea();
        nameAdventure = new javax.swing.JLabel();
        quickly = new javax.swing.JButton();
        readyToGo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Описание эпизода...");
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        start.setBackground(new java.awt.Color(52, 90, 162));
        start.setForeground(new java.awt.Color(230, 229, 229));
        start.setText("Погнали!");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        jPanel1.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 159, 82));

        textAdventure.setEditable(false);
        textAdventure.setColumns(20);
        textAdventure.setLineWrap(true);
        textAdventure.setRows(5);
        textAdventure.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textAdventure);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 290, 200));

        nameAdventure.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        nameAdventure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameAdventure.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(nameAdventure, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 480, 40));

        quickly.setBackground(new java.awt.Color(52, 90, 162));
        quickly.setForeground(new java.awt.Color(230, 229, 229));
        quickly.setText("Да я в курсе уже, поехали дальше!");
        quickly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quicklyActionPerformed(evt);
            }
        });
        jPanel1.add(quickly, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 240, 40));

        readyToGo.setBackground(new java.awt.Color(52, 90, 162));
        readyToGo.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        readyToGo.setForeground(new java.awt.Color(230, 229, 229));
        readyToGo.setText("Если готов, то жми!");
        readyToGo.setEnabled(false);
        readyToGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readyToGoActionPerformed(evt);
            }
        });
        jPanel1.add(readyToGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 160, 80));

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Materials/JPG/game_adventure.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_startActionPerformed
    {//GEN-HEADEREND:event_startActionPerformed
        Sound_Player.playMusicPlayer1("src\\\\Materials\\\\Sounds\\\\sounds\\\\game_adventure_button-pognaly.mp3");
        Background.playMusic("src\\\\Materials\\\\Sounds\\\\sounds\\\\game_adventure_back.mp3");
        textAdventure.setText("");  
        Background.writeTextForAdventure(gChapter.getTextWithAdventure(), textAdventure);
        quickly.setEnabled(true);
        start.setEnabled(false);
        
    }//GEN-LAST:event_startActionPerformed

    private void quicklyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_quicklyActionPerformed
    {//GEN-HEADEREND:event_quicklyActionPerformed
      Sound_Player.playMusicPlayer1("src\\\\Materials\\\\Sounds\\\\sounds\\\\game_adventure_button-dayavkurseuzhe.mp3");
      Sound_Player.stopMusic();
      game = new Game();
      Background.stopGame();
      textAdventure.setText(String.valueOf(gChapter.getTextWithAdventure()));
      quickly.setEnabled(false);
      addTextToButton();      
      this.setVisible(false);
      game.setVisible(true);
      Game.answerNPC.setText(gChapter.getWordsNPC());
      game = null;
    }//GEN-LAST:event_quicklyActionPerformed

    private void readyToGoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_readyToGoActionPerformed
    {//GEN-HEADEREND:event_readyToGoActionPerformed
    Sound_Player.playMusicPlayer1("src\\\\Materials\\\\Sounds\\\\sounds\\\\game_adventure_button-elsligotovtozhmi.mp3");
    Sound_Player.stopMusic(); 
    game = new Game();
     this.setVisible(false);
     addTextToButton();
     game.setVisible(true);
     Game.answerNPC.setText(gChapter.getWordsNPC());
     game = null;
    }//GEN-LAST:event_readyToGoActionPerformed

    
     public void createNameChapter()
      {
        switch(Game_Adventure.level)
        {
            case 1:
                gChapter = new Game_Chapter_1();                              
                nameAdventure.setText(gChapter.setNameChapter());   
                break;
            case 2:
                gChapter = new Game_Chapter_2();              
                nameAdventure.setText(gChapter.setNameChapter());   
                break;
            case 3:
                gChapter = new Game_Chapter_3();                    
                nameAdventure.setText(gChapter.setNameChapter());   
                break;
            case 4:
                gChapter = new Game_Chapter_4();                  
                nameAdventure.setText(gChapter.setNameChapter());   
                break;
            case 5:
                gChapter = new Game_Chapter_5();                
                nameAdventure.setText(gChapter.setNameChapter());   
                break;
            case 6:
                gChapter = new Game_Chapter_6();              
                nameAdventure.setText(gChapter.setNameChapter());   
                break;
            case 7:
                gChapter = new Game_Chapter_7();             
                nameAdventure.setText(gChapter.setNameChapter());   
                break;
           case 8:
                gChapter = new Game_Chapter_8();            
                nameAdventure.setText(gChapter.setNameChapter());   
                break;
            case 9:
                gChapter = new Game_Chapter_9();              
                nameAdventure.setText(gChapter.setNameChapter());   
                break;
                
                
                
        }
        gChapter.addElementsForCollections();
        gChapter.addGoodAnswerNPC();
        gChapter.addBadAnswerNPC();
        
        gChapter.addTextWithAdventure();
        gChapter.addAnswerAdventure();
        gChapter.addBadEndGame();
        gChapter.addWrongAnswer();
        gChapter.addWordsNPC();
      }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[])
//      {
//        /*
//         * Set the Nimbus look and feel
//         */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the
//         * default look and feel. For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Game_Adventure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Game_Adventure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Game_Adventure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Game_Adventure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /*
//         * Create and display the form
//         */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run()
//              {
//                new Game_Adventure().setVisible(true);
//              }
//        });
//      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel nameAdventure;
    public static javax.swing.JButton quickly;
    public static javax.swing.JButton readyToGo;
    public javax.swing.JButton start;
    private javax.swing.JTextArea textAdventure;
    // End of variables declaration//GEN-END:variables
}
